### ISSUE TITLE
Замечания по TV

### ISSUE THREAD

**Issue by alexey-malov** [lezhnina-anna/oop#11]
```
1>c:\teaching\2018\oop\lezhnina\oop\lab03\tvset\remotecontrol.cpp(61): warning C4715: 'CRemoteControl::SelectChannel': not all control paths return a value
1>c:\teaching\2018\oop\lezhnina\oop\lab03\tvset\remotecontrol.cpp(75): warning C4715: 'CRemoteControl::SelectPreviousChannel': not all control paths return a value
```

- [x] не должно быть предупреждений

**Comment by alexey-malov** [comment]
- [x] Повторный вызов SelectPreviousChannel должен возвращать канал, который был до этого

**Comment by alexey-malov** [comment]
```
> ^Z
Unknown command!
```

- [x] В процессе диалога с программой ввод символа конца файла должен приводить к молчаливому выходу без попытки интерпретировать ввод команду

**Comment by alexey-malov** [comment]
```
> ^Z
Unknown command!
```

- [x] В процессе диалога с программой ввод символа конца файла должен приводить к молчаливому выходу без попытки интерпретировать как команду

**Comment by alexey-malov** [comment]
```
2>main.cpp(9): warning C4326: return type of 'main' should be 'int' instead of 'void'
```

- [x] Не должно быть warning-ов

**Comment by oMystique** [comment]
- [ ] Магические числа лучше вынести в константы (именованные)
`100, 0`

**Comment by alexey-malov** [comment]
```c++
const int MAX_CHANNEL_NUMBER = 100;
const int MIN_CHANNEL_NUMBER = 0;
```

- [x] Валидные имена каналов не могут быть равны 0 и 100
